const express = require("express");
const { query } = require("./db");
const { authenticate, requireRole, hashPassword } = require("./auth");
const router = express.Router();
router.use(authenticate, requireRole("ADMIN"));

router.get("/roles", async (req,res,next)=>{try{res.json((await query("SELECT id,name,description FROM roles ORDER BY name")).rows)}catch(e){next(e)}});
router.post("/users", async (req,res,next)=>{try{const {username,password,fullName,mobile,email,roleId,officeId}=req.body||{};if(!username||!password||!fullName||!roleId)return res.status(400).json({error:"username, password, fullName and roleId are required"});const r=await query(`INSERT INTO users(username,password_hash,full_name,mobile,email,role_id,office_id) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING id,username,full_name,mobile,email,role_id,office_id,active,created_at`,[username,await hashPassword(password),fullName,mobile||null,email||null,roleId,officeId||null]);res.status(201).json(r.rows[0])}catch(e){next(e)}});
router.patch("/users/:id", async(req,res,next)=>{try{const {fullName,mobile,email,roleId,officeId,active,password}=req.body||{};const f=[],p=[];const add=(k,v)=>{p.push(v);f.push(`${k}=$${p.length}`)};if(fullName!==undefined)add("full_name",fullName);if(mobile!==undefined)add("mobile",mobile);if(email!==undefined)add("email",email);if(roleId!==undefined)add("role_id",roleId);if(officeId!==undefined)add("office_id",officeId);if(active!==undefined)add("active",active);if(password)add("password_hash",await hashPassword(password));if(!f.length)return res.status(400).json({error:"No fields to update"});p.push(req.params.id);const r=await query(`UPDATE users SET ${f.join(",")},updated_at=NOW() WHERE id=$${p.length} RETURNING id,username,full_name,mobile,email,role_id,office_id,active,updated_at`,p);if(!r.rows[0])return res.status(404).json({error:"User not found"});res.json(r.rows[0])}catch(e){next(e)}});
router.post("/offices", async(req,res,next)=>{try{const {name,code,parentOfficeId,address}=req.body||{};if(!name)return res.status(400).json({error:"name is required"});const r=await query(`INSERT INTO offices(name,code,parent_office_id,address) VALUES($1,$2,$3,$4) RETURNING *`,[name,code||null,parentOfficeId||null,address||null]);res.status(201).json(r.rows[0])}catch(e){next(e)}});
router.patch("/offices/:id", async(req,res,next)=>{try{const {name,code,parentOfficeId,address,active}=req.body||{};const r=await query(`UPDATE offices SET name=COALESCE($1,name),code=COALESCE($2,code),parent_office_id=$3,address=COALESCE($4,address),active=COALESCE($5,active) WHERE id=$6 RETURNING *`,[name||null,code||null,parentOfficeId||null,address||null,active,req.params.id]);if(!r.rows[0])return res.status(404).json({error:"Office not found"});res.json(r.rows[0])}catch(e){next(e)}});
module.exports=router;
