const express = require("express");
const { pool, query } = require("./db");
const { login, authenticate, requireRole } = require("./auth");
const router = express.Router();

router.post("/auth/login", async (req,res,next)=>{try{const {username,password}=req.body||{};if(!username||!password)return res.status(400).json({error:"Username and password are required"});const result=await login(username,password);if(!result)return res.status(401).json({error:"Invalid username or password"});res.json(result)}catch(e){next(e)}});
router.get("/auth/me",authenticate,(req,res)=>res.json({user:req.user}));
router.get("/offices",authenticate,async(req,res,next)=>{try{res.json((await query("SELECT id,name,code,parent_office_id,address,active FROM offices WHERE active=TRUE ORDER BY name")).rows)}catch(e){next(e)}});
router.get("/users",authenticate,async(req,res,next)=>{try{const p=[];let w="u.active=TRUE";if(req.query.officeId){p.push(req.query.officeId);w+=` AND u.office_id=$${p.length}`}res.json((await query(`SELECT u.id,u.username,u.full_name,u.mobile,u.email,u.office_id,r.name role_name,o.name office_name FROM users u JOIN roles r ON r.id=u.role_id LEFT JOIN offices o ON o.id=u.office_id WHERE ${w} ORDER BY u.full_name`,p)).rows)}catch(e){next(e)}});
router.get("/dashboard/summary",authenticate,async(req,res,next)=>{try{res.json((await query(`SELECT COUNT(*)::int total,COUNT(*) FILTER(WHERE status='RECEIVED')::int received,COUNT(*) FILTER(WHERE status='FORWARDED')::int forwarded,COUNT(*) FILTER(WHERE status='PENDING')::int pending,COUNT(*) FILTER(WHERE status='DISPOSED')::int disposed,COUNT(*) FILTER(WHERE due_date<CURRENT_DATE AND status NOT IN('DISPOSED','CLOSED'))::int overdue FROM dak`)).rows[0])}catch(e){next(e)}});
router.get("/reports/dak",authenticate,async(req,res,next)=>{try{const {from,to,status,officeId}=req.query,p=[],w=[];if(from){p.push(from);w.push(`d.received_at::date>=$${p.length}`)}if(to){p.push(to);w.push(`d.received_at::date<=$${p.length}`)}if(status){p.push(status);w.push(`d.status=$${p.length}`)}if(officeId){p.push(officeId);w.push(`d.current_office_id=$${p.length}`)}const r=await query(`SELECT d.dak_number,d.subject,d.sender_name,d.received_at,d.priority,d.status,o.name office_name,u.full_name current_user_name,d.due_date FROM dak d LEFT JOIN offices o ON o.id=d.current_office_id LEFT JOIN users u ON u.id=d.current_user_id ${w.length?"WHERE "+w.join(" AND "):""} ORDER BY d.received_at DESC LIMIT 5000`,p);res.json(r.rows)}catch(e){next(e)}});
router.get("/dak",authenticate,async(req,res,next)=>{try{const {status,officeId,userId,search,limit=50,offset=0}=req.query,p=[],w=[];if(status){p.push(status);w.push(`d.status=$${p.length}`)}if(officeId){p.push(officeId);w.push(`d.current_office_id=$${p.length}`)}if(userId){p.push(userId);w.push(`d.current_user_id=$${p.length}`)}if(search){p.push(`%${search}%`);w.push(`(d.dak_number ILIKE $${p.length} OR d.subject ILIKE $${p.length} OR d.sender_name ILIKE $${p.length})`)}p.push(Math.min(Math.max(Number(limit)||50,1),200));const lp=p.length;p.push(Math.max(Number(offset)||0,0));const op=p.length;res.json((await query(`SELECT d.*,o.name current_office_name,u.full_name current_user_name FROM dak d LEFT JOIN offices o ON o.id=d.current_office_id LEFT JOIN users u ON u.id=d.current_user_id ${w.length?"WHERE "+w.join(" AND "):""} ORDER BY d.received_at DESC LIMIT $${lp} OFFSET $${op}`,p)).rows)}catch(e){next(e)}});
router.get("/dak/:id",authenticate,async(req,res,next)=>{try{const d=(await query(`SELECT d.*,o.name current_office_name,u.full_name current_user_name FROM dak d LEFT JOIN offices o ON o.id=d.current_office_id LEFT JOIN users u ON u.id=d.current_user_id WHERE d.id=$1`,[req.params.id])).rows[0];if(!d)return res.status(404).json({error:"Dak not found"});const m=(await query(`SELECT m.*,fo.name from_office_name,too.name to_office_name,fu.full_name from_user_name,tu.full_name to_user_name FROM dak_movements m LEFT JOIN offices fo ON fo.id=m.from_office_id LEFT JOIN offices too ON too.id=m.to_office_id LEFT JOIN users fu ON fu.id=m.from_user_id LEFT JOIN users tu ON tu.id=m.to_user_id WHERE m.dak_id=$1 ORDER BY m.acted_at DESC`,[req.params.id])).rows;res.json({dak:d,movements:m})}catch(e){next(e)}});
router.post("/dak",authenticate,requireRole("ADMIN","OFFICER","OPERATOR"),async(req,res,next)=>{try{const {dakNumber,subject,senderName,senderAddress,receivedMode,priority,officeId,dueDate,remarks}=req.body||{};if(!dakNumber||!subject)return res.status(400).json({error:"dakNumber and subject are required"});const c=await pool.connect();try{await c.query("BEGIN");const d=(await c.query(`INSERT INTO dak(dak_number,subject,sender_name,sender_address,received_mode,priority,current_office_id,due_date,remarks,created_by) VALUES($1,$2,$3,$4,$5,COALESCE($6,'NORMAL'),$7,$8,$9,$10) RETURNING *`,[dakNumber,subject,senderName||null,senderAddress||null,receivedMode||null,priority||null,officeId||null,dueDate||null,remarks||null,req.user.sub])).rows[0];await c.query(`INSERT INTO dak_movements(dak_id,to_office_id,action,remarks) VALUES($1,$2,'REGISTERED',$3)`,[d.id,officeId||null,remarks||null]);await c.query("COMMIT");res.status(201).json(d)}catch(e){await c.query("ROLLBACK");throw e}finally{c.release()}}catch(e){next(e)}});
router.post("/dak/:id/move",authenticate,requireRole("ADMIN","OFFICER"),async(req,res,next)=>{try{const {toOfficeId,toUserId,remarks}=req.body||{};if(!toOfficeId&&!toUserId)return res.status(400).json({error:"Destination office or user is required"});const c=await pool.connect();try{await c.query("BEGIN");const d=(await c.query("SELECT * FROM dak WHERE id=$1 FOR UPDATE",[req.params.id])).rows[0];if(!d){await c.query("ROLLBACK");return res.status(404).json({error:"Dak not found"})}const office=toOfficeId||d.current_office_id,user=toUserId||null;const u=(await c.query(`UPDATE dak SET current_office_id=$1,current_user_id=$2,status='FORWARDED',updated_at=NOW() WHERE id=$3 RETURNING *`,[office,user,d.id])).rows[0];await c.query(`INSERT INTO dak_movements(dak_id,from_office_id,to_office_id,from_user_id,to_user_id,action,remarks) VALUES($1,$2,$3,$4,$5,'FORWARDED',$6)`,[d.id,d.current_office_id,office,req.user.sub,user,remarks||null]);await c.query("COMMIT");res.json(u)}catch(e){await c.query("ROLLBACK");throw e}finally{c.release()}}catch(e){next(e)}});
router.post("/dak/:id/status",authenticate,requireRole("ADMIN","OFFICER","OPERATOR"),async(req,res,next)=>{try{const {status,remarks}=req.body||{},allowed=["RECEIVED","PENDING","FORWARDED","DISPOSED","CLOSED"];if(!allowed.includes(status))return res.status(400).json({error:"Invalid status"});const c=await pool.connect();try{await c.query("BEGIN");const d=(await c.query("SELECT * FROM dak WHERE id=$1 FOR UPDATE",[req.params.id])).rows[0];if(!d){await c.query("ROLLBACK");return res.status(404).json({error:"Dak not found"})}const u=(await c.query("UPDATE dak SET status=$1,remarks=COALESCE($2,remarks),updated_at=NOW() WHERE id=$3 RETURNING *",[status,remarks||null,d.id])).rows[0];await c.query(`INSERT INTO dak_movements(dak_id,from_office_id,to_office_id,from_user_id,to_user_id,action,remarks) VALUES($1,$2,$2,$3,$3,$4,$5)`,[d.id,d.current_office_id,d.current_user_id,status,remarks||null]);await c.query("COMMIT");res.json(u)}catch(e){await c.query("ROLLBACK");throw e}finally{c.release()}}catch(e){next(e)}});
module.exports=router;
