import React, { useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import "./styles.css";

const API = import.meta.env.VITE_API_URL || "http://localhost:3000/api";
async function api(path, options = {}) {
  const token = localStorage.getItem("dmms_token");
  const headers = { "Content-Type": "application/json", ...(options.headers || {}) };
  if (token) headers.Authorization = `Bearer ${token}`;
  const response = await fetch(`${API}${path}`, { ...options, headers });
  const data = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(data.error || "Request failed");
  return data;
}

function Login({ onLogin }) {
  const [username,setUsername]=useState(""); const [password,setPassword]=useState(""); const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
  async function submit(e){e.preventDefault();setError("");setBusy(true);try{const data=await api("/auth/login",{method:"POST",body:JSON.stringify({username,password})});localStorage.setItem("dmms_token",data.token);localStorage.setItem("dmms_user",JSON.stringify(data.user));onLogin(data.user)}catch(err){setError(err.message)}finally{setBusy(false)}}
  return <div className="login-shell"><div className="login-card"><div className="brand-mark">DM</div><h1>Department Mail Management System</h1><p className="muted">Secure digital Dak management</p><form onSubmit={submit}><label>Username<input value={username} onChange={e=>setUsername(e.target.value)} required /></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required /></label>{error&&<div className="alert error">{error}</div>}<button className="primary full" disabled={busy}>{busy?"Signing in…":"Sign In"}</button></form></div></div>
}

function Dashboard({user,onLogout}){
  const [summary,setSummary]=useState(null),[dak,setDak]=useState([]),[offices,setOffices]=useState([]),[users,setUsers]=useState([]),[search,setSearch]=useState(""),[error,setError]=useState(""),[showForm,setShowForm]=useState(false),[selected,setSelected]=useState(null),[showMove,setShowMove]=useState(false),[form,setForm]=useState({dakNumber:"",subject:"",senderName:"",receivedMode:"EMAIL",priority:"NORMAL",officeId:"",remarks:""}),[move,setMove]=useState({toOfficeId:"",toUserId:"",remarks:""});
  async function load(){try{const [s,d,o,u]=await Promise.all([api("/dashboard/summary"),api(`/dak?search=${encodeURIComponent(search)}`),api("/offices"),api("/users")]);setSummary(s);setDak(d);setOffices(o);setUsers(u);setError("")}catch(err){setError(err.message)}}
  useEffect(()=>{load()},[]);
  const cards=useMemo(()=>summary?[["Total Dak",summary.total,"total"],["Received",summary.received,"received"],["Pending",summary.pending,"pending"],["Overdue",summary.overdue,"pending"],["Disposed",summary.disposed,"disposed"]]:[],[summary]);
  async function createDak(e){e.preventDefault();try{await api("/dak",{method:"POST",body:JSON.stringify(form)});setShowForm(false);setForm({dakNumber:"",subject:"",senderName:"",receivedMode:"EMAIL",priority:"NORMAL",officeId:"",remarks:""});await load()}catch(err){setError(err.message)}}
  async function openDak(id){try{setSelected(await api(`/dak/${id}`))}catch(err){setError(err.message)}}
  async function moveDak(e){e.preventDefault();try{await api(`/dak/${selected.dak.id}/move`,{method:"POST",body:JSON.stringify(move)});setShowMove(false);setMove({toOfficeId:"",toUserId:"",remarks:""});await openDak(selected.dak.id);await load()}catch(err){setError(err.message)}}
  async function setStatus(status){try{await api(`/dak/${selected.dak.id}/status`,{method:"POST",body:JSON.stringify({status})});await openDak(selected.dak.id);await load()}catch(err){setError(err.message)}}
  function logout(){localStorage.removeItem("dmms_token");localStorage.removeItem("dmms_user");onLogout()}
  return <div className="app-shell"><header className="topbar"><div className="brand"><span className="brand-dot">DM</span><span>DMMS</span></div><div className="user-area"><span>{user.fullName||user.username}</span><span className="role">{user.role}</span><button className="ghost" onClick={logout}>Logout</button></div></header><aside className="sidebar"><div className="nav active">▣ Dashboard</div><div className="nav">✉ Inward Dak</div><div className="nav">↗ Outward Dak</div><div className="nav">↔ Movement & Tracking</div><div className="nav">▤ Reports</div><div className="nav">⚙ Administration</div></aside><main className="content"><div className="page-head"><div><h2>Dashboard</h2><p className="muted">Department mail overview and Dak workflow</p></div><button className="primary" onClick={()=>setShowForm(true)}>+ New Inward Dak</button></div>{error&&<div className="alert error">{error}</div>}<section className="cards">{cards.map(([label,value,type])=><div className={`stat ${type}`} key={label}><span>{label}</span><strong>{value}</strong></div>)}</section><section className="panel"><div className="panel-head"><h3>Recent Dak</h3><input className="search" placeholder="Search Dak no., subject or sender" value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==="Enter"&&load()}/></div><div className="table-wrap"><table><thead><tr><th>Dak No.</th><th>Subject</th><th>Sender</th><th>Received</th><th>Status</th><th>Current User</th><th>Action</th></tr></thead><tbody>{dak.map(d=><tr key={d.id}><td><b>{d.dak_number}</b></td><td>{d.subject}</td><td>{d.sender_name||"—"}</td><td>{new Date(d.received_at).toLocaleDateString()}</td><td><span className={`badge ${String(d.status).toLowerCase()}`}>{d.status}</span></td><td>{d.current_user_name||d.current_office_name||"—"}</td><td><button className="small-btn" onClick={()=>openDak(d.id)}>View</button></td></tr>)}{!dak.length&&<tr><td colSpan="7" className="empty">No Dak records found.</td></tr>}</tbody></table></div></section></main>
    {showForm&&<div className="modal-backdrop"><form className="modal" onSubmit={createDak}><div className="modal-head"><h3>Register Inward Dak</h3><button type="button" className="icon" onClick={()=>setShowForm(false)}>×</button></div><div className="form-grid"><label>Dak Number<input required value={form.dakNumber} onChange={e=>setForm({...form,dakNumber:e.target.value})}/></label><label>Priority<select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}><option>NORMAL</option><option>HIGH</option><option>URGENT</option></select></label><label className="wide">Subject<input required value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})}/></label><label>Sender Name<input value={form.senderName} onChange={e=>setForm({...form,senderName:e.target.value})}/></label><label>Received Mode<select value={form.receivedMode} onChange={e=>setForm({...form,receivedMode:e.target.value})}><option>EMAIL</option><option>POST</option><option>BY_HAND</option><option>PORTAL</option></select></label><label>Office<select value={form.officeId} onChange={e=>setForm({...form,officeId:e.target.value})}><option value="">Select office</option>{offices.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><label className="wide">Remarks<textarea value={form.remarks} onChange={e=>setForm({...form,remarks:e.target.value})}/></label></div><div className="modal-actions"><button type="button" className="ghost" onClick={()=>setShowForm(false)}>Cancel</button><button className="primary">Register Dak</button></div></form></div>}
    {selected&&<div className="modal-backdrop"><div className="modal detail-modal"><div className="modal-head"><div><h3>{selected.dak.dak_number}</h3><p className="muted">{selected.dak.subject}</p></div><button className="icon" onClick={()=>setSelected(null)}>×</button></div><div className="detail-grid"><div><b>Sender</b><span>{selected.dak.sender_name||"—"}</span></div><div><b>Status</b><span className="badge">{selected.dak.status}</span></div><div><b>Current Office</b><span>{selected.dak.current_office_name||"—"}</span></div><div><b>Current User</b><span>{selected.dak.current_user_name||"—"}</span></div><div><b>Priority</b><span>{selected.dak.priority}</span></div><div><b>Due Date</b><span>{selected.dak.due_date||"—"}</span></div></div><h4>Movement History</h4><div className="timeline">{selected.movements.map(m=><div className="timeline-item" key={m.id}><b>{m.action}</b><span>{m.from_office_name||"—"} → {m.to_office_name||"—"}</span><small>{new Date(m.acted_at).toLocaleString()} {m.remarks?`• ${m.remarks}`:""}</small></div>)}</div><div className="modal-actions"><button className="ghost" onClick={()=>setStatus("PENDING")}>Mark Pending</button><button className="ghost" onClick={()=>setStatus("RECEIVED")}>Mark Received</button><button className="ghost" onClick={()=>setShowMove(true)}>Forward / Assign</button><button className="primary" onClick={()=>setStatus("DISPOSED")}>Dispose</button></div></div></div>}
    {showMove&&selected&&<div className="modal-backdrop"><form className="modal small-modal" onSubmit={moveDak}><div className="modal-head"><h3>Forward / Assign Dak</h3><button type="button" className="icon" onClick={()=>setShowMove(false)}>×</button></div><label>Destination Office<select required value={move.toOfficeId} onChange={e=>setMove({...move,toOfficeId:e.target.value})}><option value="">Select office</option>{offices.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><label>Assign User<select value={move.toUserId} onChange={e=>setMove({...move,toUserId:e.target.value})}><option value="">No specific user</option>{users.filter(u=>!move.toOfficeId||u.office_id===move.toOfficeId).map(u=><option key={u.id} value={u.id}>{u.full_name} — {u.role_name}</option>)}</select></label><label>Remarks<textarea value={move.remarks} onChange={e=>setMove({...move,remarks:e.target.value})}/></label><div className="modal-actions"><button type="button" className="ghost" onClick={()=>setShowMove(false)}>Cancel</button><button className="primary">Forward Dak</button></div></form></div>}
  </div>
}
function App(){const [user,setUser]=useState(()=>JSON.parse(localStorage.getItem("dmms_user")||"null"));return user?<Dashboard user={user} onLogout={()=>setUser(null)}/>:<Login onLogin={setUser}/>}
createRoot(document.getElementById("root")).render(<React.StrictMode><App/></React.StrictMode>);
